# Generated by Django 6.0.8 on 2026-08-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_notification_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего напоминания'),
        ),
    ]
